name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install Dependencies
        working-directory: ./server
        run: npm ci
        
      - name: Run Tests
        working-directory: ./server
        run: npm test -- --watchAll=false
        
      - name: Deploy to Railway
        uses: railwayapp/action@v1.0.0
        with:
          service: backend
          environment: production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
